services:
  # postgresql database service
  db:
    image: postgres:16-alpine
    container_name: oauth_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oauth_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: oauth_app
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      - ENV=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/oauth_db
      - DATABASE_SYNC_URL=postgresql://postgres:postgres@db:5432/oauth_db

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

    command: >
      sh -c "
        echo 'Starting application...' &&
        uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  migrate:
    build: .
    container_name: oauth_migrate
    environment:
      - ENV=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/oauth_db
      - DATABASE_SYNC_URL=postgresql://postgres:postgres@db:5432/oauth_db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "uv run alembic upgrade head"
    volumes:
      - .:/app

volumes:
  postgres_data:
