"""Add complete OAuth 2.0 models with organizations and scopes

Revision ID: 0b7a2cb8d0c2
Revises: c6fafc3bf4b4
Create Date: 2025-08-09 16:11:18.676498+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7a2cb8d0c2'
down_revision: Union[str, Sequence[str], None] = 'c6fafc3bf4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('given_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('family_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('locale', sa.String(length=10), server_default='en', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_active_superuser', 'users', ['is_active', 'is_superuser'], unique=False)
    op.create_index('ix_users_email_verified', 'users', ['email_verified'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email_verified', table_name='users')
    op.drop_index('ix_users_active_superuser', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    # ### end Alembic commands ###
