"""Add OAuth 2.0 models: clients, tokens, scopes, and audit logs

Revision ID: acd9274d577b
Revises: 5e7f8249a083
Create Date: 2025-08-09 16:28:42.417575+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd9274d577b'
down_revision: Union[str, Sequence[str], None] = '5e7f8249a083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scopes',
    sa.Column('id', sa.String(length=100), nullable=False, comment="Technical scope identifier (e.g., 'read:messages', 'admin:organization')"),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('OPENID', 'PROFILE', 'CHAT', 'ADMIN', name='scopecategoryenum'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_consent', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('organization_specific', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this scope is available for use'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.Enum('CONFIDENTIAL', 'PUBLIC', name='clienttypeenum'), nullable=False),
    sa.Column('grant_types', sa.JSON(), nullable=False),
    sa.Column('response_types', sa.JSON(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('allowed_scopes', sa.JSON(), nullable=False),
    sa.Column('default_scopes', sa.JSON(), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTRATION', 'LOGIN_FAILED', 'TOKEN_ISSUED', 'TOKEN_REFRESHED', 'TOKEN_REVOKED', 'AUTHORIZATION_GRANTED', 'AUTHORIZATION_DENIED', 'CLIENT_REGISTERED', 'CLIENT_UPDATED', 'CLIENT_DELETED', 'USER_ROLE_CHANGED', 'PASSWORD_RESET', 'EMAIL_VERIFIED', 'ACCOUNT_LOCKED', 'SECURITY_BREACH', 'SUSPICIOUS_ACTIVITY', name='auditeventtype'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'WARNING', name='auditstatus'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('authorization_codes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('scope', sa.String(length=1000), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('nonce', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(code_challenge IS NULL AND code_challenge_method IS NULL) OR (code_challenge IS NOT NULL AND code_challenge_method IS NOT NULL)', name='ck_auth_codes_pkce_consistency'),
    sa.CheckConstraint('expires_at > created_at', name='ck_auth_codes_valid_expiry'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=1000), nullable=False),
    sa.Column('rotation_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_refresh_tokens_valid_expiry'),
    sa.CheckConstraint('rotation_count >= 0', name='ck_refresh_tokens_rotation_count'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_table('refresh_tokens')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('oauth_clients')
    op.drop_table('scopes')
    # ### end Alembic commands ###
