"""Fix OAuth model relationships and data types

Revision ID: 3b354574c2f2
Revises: b58b5e883e6e
Create Date: 2025-08-09 17:02:10.812226+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b354574c2f2'
down_revision: Union[str, Sequence[str], None] = 'b58b5e883e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.VARCHAR(length=26),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=26),
               existing_nullable=False)
    # ### end Alembic commands ###
